##
## EPITECH PROJECT, 2022
## 307multigrains
## File description:
## Makefile
##

default: copy

all: default

copy:
	cp main.py 307multigrains
	chmod +x 307multigrains

clean:
	@echo "You launched clean but nothing seems to have happened..."

fclean:
	rm -f 307multigrains

re:
	$(MAKE) fclean
	$(MAKE) default
