##
## EPITECH PROJECT, 2022
## 309pollution
## File description:
## Makefile
##

default: copy

all: default

copy:
	cp main.py 309pollution
	chmod +x 309pollution

clean:
	@echo "You launched clean but nothing seems to have happened..."

fclean:
	rm -f 309pollution

re:
	$(MAKE) fclean
	$(MAKE) default
