#!/usr/bin/env python3

import sys
from makefile import Makefile


def print_usage() -> None:
    print("USAGE")
    print("\t./303make makefile [file]")
    print("DESCRIPTION")
    print("\tmakefile\tname of the makefile")
    print("\tfile\t\tname of a recently modified file")


if __name__ == "__main__":
    try:
        if len(sys.argv) == 2 and sys.argv[1] == "-h":
            # print help
            print_usage()
        elif len(sys.argv) == 2:
            # print graph
            m = Makefile(sys.argv[1])
            m.printGraph()
        elif len(sys.argv) == 3:
            # print dependencies
            m = Makefile(sys.argv[1])
            m.printDependencies(sys.argv[2])
        else:
            raise Exception('Wrong number of arguments')
    except Exception as e:
        print(e, file=sys.stderr)
        print('Try ./303make -h', file=sys.stderr)
        sys.exit(84)
